INFO 2020-09-22 01:07:08,100 autoreload 6852 10088 Watching for file changes with StatReloader
INFO 2020-09-22 01:09:05,865 basehttp 6852 14140 "GET /shopping-cart/ HTTP/1.1" 200 28140
INFO 2020-09-22 01:09:06,018 basehttp 6852 14140 "GET /static/css/base.css HTTP/1.1" 304 0
INFO 2020-09-22 01:09:06,026 basehttp 6852 14140 "GET /static/js/app.js HTTP/1.1" 304 0
INFO 2020-09-22 01:09:11,937 basehttp 6852 2596 "GET /api/extra-items HTTP/1.1" 200 1526
INFO 2020-09-22 01:09:12,062 basehttp 6852 14140 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:09:12,241 basehttp 6852 2596 "GET /media/shop/3_NthBVI8.jpg HTTP/1.1" 304 0
INFO 2020-09-22 01:09:12,309 basehttp 6852 2596 "GET /media/shop/6_JFGaN0Q.jpg HTTP/1.1" 304 0
INFO 2020-09-22 01:09:13,615 basehttp 6852 14140 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:09:43,625 basehttp 6852 3220 "GET /shopping-cart/ HTTP/1.1" 200 28133
INFO 2020-09-22 01:09:45,853 basehttp 6852 3168 "GET /api/extra-items HTTP/1.1" 200 1526
INFO 2020-09-22 01:09:45,986 basehttp 6852 5664 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:09:46,881 basehttp 6852 5664 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:09:59,949 basehttp 6852 2520 "GET /photoshop-templates/ HTTP/1.1" 200 26006
INFO 2020-09-22 01:10:01,685 basehttp 6852 2520 "GET /api/photoshop-list HTTP/1.1" 200 2156
INFO 2020-09-22 01:10:01,727 basehttp 6852 2520 "GET /media/shop/4_GVAzah3.jpg HTTP/1.1" 304 0
INFO 2020-09-22 01:10:01,741 basehttp 6852 2520 "GET /media/shop/5_bJA3kZ9.png HTTP/1.1" 304 0
INFO 2020-09-22 01:10:02,189 basehttp 6852 13872 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:10:15,168 basehttp 6852 13796 "GET /lightroom-presets/ HTTP/1.1" 200 26013
INFO 2020-09-22 01:10:15,267 basehttp 6852 13796 "GET /static/js/app.js HTTP/1.1" 304 0
INFO 2020-09-22 01:10:17,053 basehttp 6852 13796 "GET /api/lightroom-list HTTP/1.1" 200 2291
INFO 2020-09-22 01:10:17,518 basehttp 6852 12820 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:10:44,750 basehttp 6852 2280 "POST /auth/login/ HTTP/1.1" 200 50
WARNING 2020-09-22 01:11:05,345 log 6852 13856 Unauthorized: /confirm-email/
WARNING 2020-09-22 01:11:05,345 basehttp 6852 13856 "GET /confirm-email/ HTTP/1.1" 401 27
WARNING 2020-09-22 01:11:22,138 log 6852 2520 Forbidden: /auth/registration/
WARNING 2020-09-22 01:11:22,140 basehttp 6852 2520 "POST /auth/registration/ HTTP/1.1" 403 58
INFO 2020-09-22 01:17:55,725 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:56,311 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:57,107 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:17:57,132 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:57,702 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:58,148 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:17:58,347 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:58,855 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:59,068 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:17:59,320 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:17:59,903 basehttp 6852 14224 "GET /api/add-to-cart/pop-color-preset-1 HTTP/1.1" 200 57
INFO 2020-09-22 01:18:00,003 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:18:00,603 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:18:01,225 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:18:01,765 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
INFO 2020-09-22 01:18:02,367 basehttp 6852 11488 "GET /api/cart-list HTTP/1.1" 200 2213
WARNING 2020-09-22 01:18:20,973 log 6852 11424 Forbidden: /auth/registration/
WARNING 2020-09-22 01:18:20,973 basehttp 6852 11424 "POST /auth/registration/ HTTP/1.1" 403 58
WARNING 2020-09-22 01:18:29,280 log 6852 12224 Forbidden: /auth/registration/
WARNING 2020-09-22 01:18:29,280 basehttp 6852 12224 "POST /auth/registration/ HTTP/1.1" 403 58
INFO 2020-09-22 12:26:37,006 autoreload 7776 11336 Watching for file changes with StatReloader
INFO 2020-09-22 12:26:43,591 basehttp 7776 4764 "GET / HTTP/1.1" 200 27314
INFO 2020-09-22 12:26:43,758 basehttp 7776 4764 "GET /static/lib/scss/image-comparison.scss HTTP/1.1" 304 0
INFO 2020-09-22 12:26:43,759 basehttp 7776 12628 "GET /static/css/base.css HTTP/1.1" 304 0
INFO 2020-09-22 12:26:43,946 basehttp 7776 12628 "GET /static/js/base.js HTTP/1.1" 304 0
INFO 2020-09-22 12:26:44,013 basehttp 7776 4764 "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 14984
INFO 2020-09-22 12:26:44,039 basehttp 7776 4764 "GET /static/js/app.js HTTP/1.1" 304 0
INFO 2020-09-22 12:26:44,056 basehttp 7776 12628 "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 12791
INFO 2020-09-22 12:26:44,067 basehttp 7776 4764 "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404
INFO 2020-09-22 12:26:45,573 basehttp 7776 10540 "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882
INFO 2020-09-22 12:26:45,575 basehttp 7776 13372 "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41
WARNING 2020-09-22 12:26:45,693 basehttp 7776 13372 "GET /static/img/favicon.ico HTTP/1.1" 404 1772
ERROR 2020-09-22 12:26:51,824 log 7776 2388 Internal Server Error: /api/cart-list
Traceback (most recent call last):
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\contrib\auth\models.py", line 414, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\dev\webapps\mavshop\core\api\views.py", line 20, in order_list
    queryset = Order.objects.filter(user=request.user, ordered=False)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\marka\.virtualenvs\mavshop-zg2IBmbO\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x05503AD8>.
ERROR 2020-09-22 12:26:52,033 basehttp 7776 2388 "GET /api/cart-list HTTP/1.1" 500 166814
